package controllers

import (
	"github.com/gin-gonic/gin"
	"packwiz-web/internal/config"
	"path/filepath"
)

type ModpackController struct{}

// ServeStatic
// serve the static files generated by the packwiz_cli cli. these are modified by
// the server process calling the cli. the root path should already exist on
// the server at start-time and is defined by PACKWIZ_DIR.
func (mc *ModpackController) ServeStatic(c *gin.Context) {
	modpack := c.Param("modpack")
	filePath := c.Param("filepath")

	absPath := filepath.Join(config.C.PackwizDir, modpack, filePath)

	c.File(absPath)
}
