/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcceptableVersions: typeof import('./components/forms/AcceptableVersions.vue')['default']
    AddCurseforge: typeof import('./components/mods/AddCurseforge.vue')['default']
    AddModForm: typeof import('./components/mods/AddModForm.vue')['default']
    AddModrinth: typeof import('./components/mods/AddModrinth.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ChangePasswordForm: typeof import('./components/user/ChangePasswordForm.vue')['default']
    ConfirmationDialog: typeof import('./components/ConfirmationDialog.vue')['default']
    CookiesWarn: typeof import('./components/CookiesWarn.vue')['default']
    FiltersMenu: typeof import('./components/FiltersMenu.vue')['default']
    Loader: typeof import('./components/forms/Loader.vue')['default']
    MinecraftVersion: typeof import('./components/forms/MinecraftVersion.vue')['default']
    ModsList: typeof import('./components/mods/ModsList.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    PackActions: typeof import('./components/pack/PackActions.vue')['default']
    PackCard: typeof import('./components/pack/PackCard.vue')['default']
    PackCreateForm: typeof import('./components/pack/PackCreateForm.vue')['default']
    PackDetails: typeof import('./components/pack/PackDetails.vue')['default']
    PackEditForm: typeof import('./components/pack/PackEditForm.vue')['default']
    PackInfoForm: typeof import('./components/pack/PackInfoForm.vue')['default']
    PackList: typeof import('./components/pack/PackList.vue')['default']
    PackStatus: typeof import('./components/pack/PackStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SlugAndName: typeof import('./components/forms/SlugAndName.vue')['default']
    ThemeSwitch: typeof import('./components/ThemeSwitch.vue')['default']
    UnderConstruction: typeof import('./components/UnderConstruction.vue')['default']
    UserList: typeof import('./components/user/UserList.vue')['default']
    UserMenu: typeof import('./components/user/UserMenu.vue')['default']
    UserProfile: typeof import('./components/user/UserProfile.vue')['default']
  }
}
