/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/admin/audit/': RouteRecordInfo<'/admin/audit/', '/admin/audit', Record<never, never>, Record<never, never>>,
    '/admin/users/': RouteRecordInfo<'/admin/users/', '/admin/users', Record<never, never>, Record<never, never>>,
    '/admin/users/[id]': RouteRecordInfo<'/admin/users/[id]', '/admin/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/users/[id].edit': RouteRecordInfo<'/admin/users/[id].edit', '/admin/users/:id/edit', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/users/new': RouteRecordInfo<'/admin/users/new', '/admin/users/new', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/packs/': RouteRecordInfo<'/packs/', '/packs', Record<never, never>, Record<never, never>>,
    '/packs/[packId]': RouteRecordInfo<'/packs/[packId]', '/packs/:packId', { packId: ParamValue<true> }, { packId: ParamValue<false> }>,
    '/packs/[packId].add-mod': RouteRecordInfo<'/packs/[packId].add-mod', '/packs/:packId/add-mod', { packId: ParamValue<true> }, { packId: ParamValue<false> }>,
    '/packs/[packId].edit': RouteRecordInfo<'/packs/[packId].edit', '/packs/:packId/edit', { packId: ParamValue<true> }, { packId: ParamValue<false> }>,
    '/packs/[packId].mod.[modId]': RouteRecordInfo<'/packs/[packId].mod.[modId]', '/packs/:packId/mod/:modId', { packId: ParamValue<true>, modId: ParamValue<true> }, { packId: ParamValue<false>, modId: ParamValue<false> }>,
    '/packs/new': RouteRecordInfo<'/packs/new', '/packs/new', Record<never, never>, Record<never, never>>,
    '/user/profile': RouteRecordInfo<'/user/profile', '/user/profile', Record<never, never>, Record<never, never>>,
  }
}
