services:
  packwiz-web:
    depends_on:
      - postgres
    #    image: ghcr.io/leocov-dev/packwiz-web:latest
    image: packwiz-web:latest
    ports:
      - "8080:8080"
    environment:
      - PWW_DATABASE=postgres
      - PWW_PG_HOST=postgres
      - PWW_PG_USER=packwiz
      - PWW_PG_PASSWORD=9r7xkPRVQjZXnCQvD1J21n0z5zxQtaGmUd1nJyzv0eU
      - PWW_PG_DBNAME=packwiz
      - PWW_SESSION_SECRET=YsGQor59TaYzgUzSQe1ycygill
      - PWW_MODE=production
      - PWW_ADMIN_PASSWORD=adminPassword1234

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=packwiz
      - POSTGRES_USER=packwiz
      - POSTGRES_PASSWORD=9r7xkPRVQjZXnCQvD1J21n0z5zxQtaGmUd1nJyzv0eU
      - TZ=Etc/UTC