name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"
          cache: true
          cache-dependency-path: "backend/go.sum"

      - name: Check Go Format
        run: cd backend && make fmtcheck

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/package.json"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"
          cache: true
          cache-dependency-path: "backend/go.sum"

      - name: Run Tests
        run: cd backend && make test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "frontend/package.json"
          cache: "npm"
          cache-dependency-path: "frontend/package-lock.json"

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "backend/go.mod"
          cache: true
          cache-dependency-path: "backend/go.sum"

      - name: Build
        run: make build-all

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build
        run: make build-image

      - name: Test Image
        run: docker run --rm packwiz-web help
