name: draft release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  release-draft:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Define Version
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          tag: ${{ steps.vars.outputs.tag }}
          version: ${{ steps.vars.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
